foreground               #C9CDD7
background               #323F46

cursor                   #C9CDD7
cursor_text_color        #323F46

url_color                #509FDE

active_border_color      #DFE2ED
inactive_border_color    #778087

bell_border_color        #F1C954

active_tab_foreground    #C9CDD7
active_tab_background    #778087
inactive_tab_foreground  #C9CDD7
inactive_tab_background  #3D4950
tab_bar_background       #3D4950

selection_foreground     #323F46
selection_background     #967C26

mark1_foreground         #323F46
mark1_background         #B26469
mark2_foreground         #323F46
mark2_background         #3E86B4
mark3_foreground         #323F46
mark3_background         #3D9074

# black
color0                   #323F46
color8                   #3D4950

# red
color1                   #83615B
color9                   #BA9088

# green
color2                   #7F9781
color10                  #BEDBC1

# yellow
color3                   #A69875
color11                  #F1DFB4

# blue
color4                   #53516F
color12                  #767495

# magenta
color5                   #856880
color13                  #BE9CB8

# cyan
color6                   #7D96B2
color14                  #BCDBFF

# white
color7                   #C9CDD7
color15                  #DFE2ED
